const candidates = {
  S:   { name: "Mette Frederiksen", party: "Socialdemokratiet", color: "#c0392b", emoji: "🌹" },
  V:   { name: "Troels Lund Poulsen", party: "Venstre", color: "#0054a6", emoji: "🔵" },
  M:   { name: "Lars Løkke Rasmussen", party: "Moderaterne", color: "#6b21a8", emoji: "🟣" },
  SF:  { name: "Pia Olsen Dyhr", party: "SF", color: "#e4007c", emoji: "🩷" },
  LA:  { name: "Alex Vanopslagh", party: "Liberal Alliance", color: "#13505b", emoji: "🏛️" },
  KF:  { name: "Mona Juul", party: "Konservative", color: "#00583c", emoji: "🌲" },
  EL:  { name: "Pelle Dragsted", party: "Enhedslisten", color: "#e6801a", emoji: "✊" },
  RV:  { name: "Martin Lidegaard", party: "Radikale Venstre", color: "#733280", emoji: "💜" },
  DF:  { name: "Morten Messerschmidt", party: "Dansk Folkeparti", color: "#c8b400", emoji: "🇩🇰" },
  DD:  { name: "Inger Støjberg", party: "Danmarksdemokraterne", color: "#00446b", emoji: "⚡" },
  ALT: { name: "Franciska Rosenkilde", party: "Alternativet", color: "#00ff7f", emoji: "🌿" },
  BP:  { name: "Lars Boje Mathiesen", party: "Borgernes Parti", color: "#d4a017", emoji: "🛡️" }
};

const fallbackDilemmas = [
  // === FLERE PENGE PÅ (invest more) vs FLERE PENGE PÅ ===
  { id: 1, type: "flere_penge_paa", category: "⚛️ Atomkraft vs. ☀️ Grøn energi", optionA: "⚛️ Byg 6-8 atomreaktorer for 120 mia. kr.", optionB: "☀️ Invester 3 mia. årligt i sol, vind og elnet", argumentA: "Stabil strøm i 60 år uden CO2. Frankrig griner af vores vindmøller når det er vindstille!", argumentB: "Sol og vind er ALLEREDE billigere end atom. Hvorfor vente 15 år på en reaktor der aldrig er færdig til tiden?", scoring: { optionA: { LA: 10, KF: 8, V: 5, DD: 5, BP: 4 }, optionB: { RV: 10, ALT: 9, SF: 8, EL: 7, S: 4 } } },
  { id: 2, type: "flere_penge_paa", category: "🎖️ Forsvar vs. 🦷 Sundhed", optionA: "🎖️ Brug 3,5% af BNP på forsvaret — 98 mia. kr.", optionB: "🦷 Gratis tandlæge og medicin til alle for 12 mia. kr.", argumentA: "Putin rykker tættere på. Vil du virkelig være det NATO-land der IKKE kan forsvare sig?", argumentB: "Folk dør af dårlige tænder og springer medicin over. 12 mia. redder tusindvis af liv!", scoring: { optionA: { LA: 10, KF: 9, V: 8, DD: 7, M: 5, BP: 5 }, optionB: { EL: 10, SF: 8, S: 7, RV: 6, ALT: 6 } } },
  { id: 3, type: "flere_penge_paa", category: "🏫 Skole vs. 🍎 Skole", optionA: "🏫 Maks 24 elever i klassen — 1,7 mia. kr.", optionB: "🍎 Gratis skolemad og kvalitetsløft — 4 mia. kr.", argumentA: "30 unger i ét lokale er KAOS. Mindre klasser = bedre læring. Giv lærerne en chance!", argumentB: "Sultne børn lærer ingenting. Gratis skolemad giver energi OG lighed. Win-win!", scoring: { optionA: { S: 10, SF: 7, EL: 7, KF: 4 }, optionB: { RV: 10, ALT: 8, SF: 7, EL: 6, S: 5 } } },
  { id: 4, type: "flere_penge_paa", category: "👷 Pension vs. ⏳ Pension", optionA: "👷 Udvid tidlig pension — nedslidte skal hvile fra 60", optionB: "⏳ Deltidspension som fleksibel alternativ", argumentA: "Mureren med ødelagte knæ har BETALT sin skat i 44 år. Lad mennesker hvile!", argumentB: "Fuld pension er for dyrt. Deltid giver ALLE mulighed for at trappe ned — smart og fleksibelt!", scoring: { optionA: { SF: 10, S: 9, DF: 9, DD: 8, EL: 8 }, optionB: { M: 10, LA: 7, V: 6, KF: 5, RV: 4 } } },
  { id: 5, type: "flere_penge_paa", category: "🚗 Biler vs. 🚌 Tog", optionA: "🚗 Afskaf registreringsafgiften — biler skal være billige", optionB: "🚌 30% billigere tog og bus i hele Danmark", argumentA: "En bil til 150.000 koster 300.000 i Danmark. Det er VANVITTIGT. Drop afgiften!", argumentB: "Grønnere, billigere, nemmere. Halvér prisen på toget og se bilen samle støv.", scoring: { optionA: { BP: 10, LA: 8, DF: 6, DD: 6, V: 5 }, optionB: { EL: 10, ALT: 10, SF: 8, RV: 7, S: 5, M: 4 } } },
  { id: 6, type: "flere_penge_paa", category: "🧓 Ældre vs. 💼 Erhverv", optionA: "🧓 6,5 mia. ekstra til ældrepleje om året", optionB: "💼 Massivt løft af erhvervsliv og iværksætteri", argumentA: "Ældre ligger i deres egen afføring og venter på hjælp. 6,5 mia. giver dem VÆRDIGHED!", argumentB: "Virksomheder skaber JOBS. Giv dem bedre vilkår og se Danmark vækste som aldrig før!", scoring: { optionA: { DF: 10, S: 8, SF: 8, DD: 7, EL: 7 }, optionB: { LA: 10, V: 9, KF: 7, M: 6, BP: 5 } } },
  { id: 7, type: "flere_penge_paa", category: "🏢 Provinsen vs. 🌐 Byen", optionA: "🏢 Flyt 10.000 statslige jobs ud af København", optionB: "🌐 Hent mere international arbejdskraft til byerne", argumentA: "København EKSPLODERER mens resten af Danmark visner. Spred arbejdspladserne NU!", argumentB: "Vi mangler hænder! Internationale talenter holder økonomien kørende. Luk op for grænsen!", scoring: { optionA: { DD: 10, DF: 9, V: 7, S: 6, KF: 5, BP: 5 }, optionB: { M: 10, RV: 7, LA: 5, ALT: 4 } } },
  { id: 8, type: "flere_penge_paa", category: "⚖️ Retssikkerhed vs. 🐷 Dyrevelfærd", optionA: "⚖️ Ny forvaltningsdomstol mod systemovergreb", optionB: "🐷 Bedre forhold for produktionsgrise", argumentA: "Staten taber TUSINDVIS af sager mod borgere. Vi har brug for en domstol der holder magten i skak!", argumentB: "33 millioner grise lever i HELVEDE. Bedre stalde, mere plads, mere anstændighed!", scoring: { optionA: { BP: 10, LA: 8, EL: 6, RV: 5, ALT: 4 }, optionB: { ALT: 10, EL: 8, SF: 7, RV: 6, S: 4 } } },
  { id: 9, type: "flere_penge_paa", category: "🎖️ Forsvar vs. 👴 Pensionister", optionA: "🎖️ Op til 2% af BNP på forsvar — brigader og kampvogne", optionB: "👴 1.000 kr. ekstra om måneden til fattige pensionister", argumentA: "NATO siger 2%. Putin siger ingenting — og det er VÆRRE. Oprust NU!", argumentB: "150.000 pensionister lever under fattigdomsgrænsen. 1.000 kr./md. giver dem værdighed!", scoring: { optionA: { KF: 10, V: 9, DD: 8, LA: 7, M: 6, BP: 5 }, optionB: { S: 10, SF: 9, DF: 8, EL: 8, ALT: 5 } } },
  { id: 10, type: "flere_penge_paa", category: "🤝 Socialpolitik vs. 👨‍👩‍👧‍👦 Kernevelfærd", optionA: "🤝 Fjern kontanthjælpsloftet — det rammer 40.000 børn", optionB: "👨‍👩‍👧‍👦 Mere kernevelfærd — trivsel for børn og omsorg for ældre", argumentA: "Børn vokser op i fattigdom PÅ GRUND AF loftet. Det er børnene der betaler prisen!", argumentB: "Skoler, daginstitutioner og plejehjem SKRIGER efter penge. Prioritér dem der allerede er i systemet!", scoring: { optionA: { SF: 10, EL: 10, ALT: 8, RV: 7, S: 5 }, optionB: { V: 9, KF: 7, DD: 7, DF: 6, M: 5, BP: 4 } } },
  { id: 11, type: "flere_penge_paa", category: "💧 Drikkevand vs. 🚗 Bilister", optionA: "💧 Rent drikkevand og natur — begræns gylleudledning", optionB: "🚗 Bilister — brændstof under 10 kr./l", argumentA: "Dit drikkevand er forurenet med sprøjtegift. Hvad nytter billig mad hvis vandet er giftigt?", argumentB: "Folk har brug for bilen! 10 kr./l er rimeligt. Stop med at straffe almindelige mennesker!", scoring: { optionA: { ALT: 10, EL: 9, RV: 7, SF: 6 }, optionB: { DF: 10, DD: 8, BP: 7, V: 5, LA: 5 } } },
  { id: 12, type: "flere_penge_paa", category: "🦷 Sundhed vs. 🎓 Uddannelse", optionA: "🦷 Gratis tandlæge og medicin til alle — 12 mia. kr.", optionB: "🎓 Stop nedskæringer på universiteter — 0,8 mia. kr.", argumentA: "Folk springer medicin over fordi de ikke har råd. I DANMARK. Det er en skandale!", argumentB: "Vi SKÆRER i de kloge hjerner der skal redde fremtiden. Stop besparelserne på uddannelse!", scoring: { optionA: { EL: 10, SF: 8, S: 7, ALT: 6 }, optionB: { RV: 10, ALT: 8, SF: 7, EL: 6, S: 5, M: 4 } } },
  { id: 13, type: "flere_penge_paa", category: "✈️ Remigration vs. 🏥 Nær sundhed", optionA: "✈️ Brug pengene på at hjemtage udlændinge — remigration", optionB: "🏥 Nær sundhedspleje til ældre uden for de store byer", argumentA: "Ikke-vestlig indvandring koster 27 mia. om året. Det er tid til at vende strømmen!", argumentB: "Din bedstemor skal ikke køre 80 km til en læge. Nær pleje redder liv i provinsen!", scoring: { optionA: { DF: 10, DD: 8, BP: 6, KF: 5, S: 4 }, optionB: { DD: 9, S: 7, SF: 7, EL: 6, RV: 5, ALT: 4 } } },

  // === FÆRRE PENGE PÅ (save/cut) vs FÆRRE PENGE PÅ ===
  { id: 14, type: "faerre_penge_paa", category: "💰 Skat vs. 💸 Skat", optionA: "💰 Formueskat på de 22.000 rigeste — 6,5 mia. kr. i kassen", optionB: "💸 Sænk indkomstskatten med 40 mia. kr. for ALLE", argumentA: "22.000 superrige betaler lidt mere, og alle andre får bedre velfærd. Ret fair, ikke?", argumentB: "DU betaler for meget i skat. 40 mia. tilbage i borgernes lommer = frihed og vækst!", scoring: { optionA: { S: 10, EL: 9, SF: 8, ALT: 6, RV: 5 }, optionB: { LA: 10, KF: 7, V: 7, M: 5, BP: 5 } } },
  { id: 15, type: "faerre_penge_paa", category: "🚜 Landbrug vs. 🧪 Miljø", optionA: "🚜 Fjern CO2-afgiften på landbrug og fiskeri", optionB: "🧪 Forbyd pesticider og beskyt drikkevandet", argumentA: "Landmanden producerer din mad! Stop med at straffe dem med afgifter — de går KONKURS!", argumentB: "Dit drikkevand er forurenet med sprøjtegift. Reelt forbud beskytter ALLE danskere!", scoring: { optionA: { DD: 10, DF: 8, V: 7, BP: 5, LA: 5 }, optionB: { ALT: 10, EL: 9, RV: 7, SF: 6 } } },
  { id: 16, type: "faerre_penge_paa", category: "🛒 Fødevarer vs. 🏘️ Bolig", optionA: "🛒 Halvér momsen på alle fødevarer — 16,8 mia. kr.", optionB: "🏘️ Boligskattestop — stop med at beskatte folks hjem", argumentA: "Maden er for DYR! Halvér momsen og giv alle familier luft i budgettet.", argumentB: "Dit hjem er ikke en PENGEAUTOMAT for staten. Stop boligskatten og lad folk bo i fred!", scoring: { optionA: { DF: 10, EL: 8, DD: 7, S: 5, BP: 4 }, optionB: { KF: 10, V: 7, LA: 6, M: 5, DD: 5, BP: 5 } } },
  { id: 17, type: "faerre_penge_paa", category: "📺 Medier vs. 🌍 Bistand", optionA: "📺 Gør DR til frivilligt abonnement — spar 1 mia.", optionB: "🌍 Skær ulandsbistanden — borgerne bestemmer selv", argumentA: "Hvorfor TVINGES du til at betale for programmer du aldrig ser? Lad folk vælge selv!", argumentB: "20,5 mia. kr. til udlandet mens vores egne ældre fryser. Lad os ordne DANMARK først!", scoring: { optionA: { BP: 10, LA: 8, DF: 5, DD: 5, V: 4 }, optionB: { BP: 8, V: 7, DF: 7, DD: 7, KF: 5, LA: 5 } } },
  { id: 18, type: "faerre_penge_paa", category: "🔧 Pension vs. 🏠 Huslejeloft", optionA: "🔧 Afskaf Arne-pension og efterløn — spar 4 mia.", optionB: "🏠 Huslejeloft — stop boligspekulanterne", argumentA: "Alle de milliarder kunne bruges på deltidspension og fleksible løsninger i stedet.", argumentB: "Udlejere hæver huslejen 20% om året. Et loft beskytter ALLE lejere mod grådighed!", scoring: { optionA: { M: 10, LA: 7, V: 6, KF: 5 }, optionB: { EL: 10, SF: 8, S: 7, ALT: 7, RV: 5 } } },
  { id: 19, type: "faerre_penge_paa", category: "🌿 Grønne afgifter vs. 🧪 Sundhedsafgifter", optionA: "🌿 Reducere grønne afgifter og klimaregulering", optionB: "🧪 Nye afgifter på pesticider, sukker og alkohol", argumentA: "Erhvervslivet KVÆLES af grønne afgifter. Lad virksomhederne ånde — de skaber dine JOBS!", argumentB: "Gift i maden, sukker i børnene og sprut i gaden. Afgifter ændrer adfærd — det virker!", scoring: { optionA: { KF: 9, V: 8, LA: 8, DD: 7, DF: 6, BP: 5 }, optionB: { RV: 10, ALT: 8, SF: 7, EL: 6, S: 4 } } },
  { id: 20, type: "faerre_penge_paa", category: "🚧 Udlændinge vs. 🛢️ Fossil energi", optionA: "🚧 Stram udlændingeydelser — besparelse fra dag ét", optionB: "🛢️ Stop fossil energi og støtte til intensivt landbrug", argumentA: "Noget for noget. Nye borgere skal BIDRAGE før de modtager. Det er kun retfærdigt!", argumentB: "Fossile subsidier er VANVID i 2026. Stop med at betale for at ødelægge planeten!", scoring: { optionA: { DD: 10, DF: 9, BP: 6, KF: 5, S: 5, V: 4 }, optionB: { ALT: 10, EL: 9, RV: 8, SF: 7, M: 4 } } },
  { id: 21, type: "faerre_penge_paa", category: "📋 Bureaukrati vs. 📋 Bureaukrati", optionA: "📋 Spar 5,5 mia. på offentlig administration", optionB: "📋 Fjern New Public Management fra det offentlige", argumentA: "Staten bruger milliarder på papirpushere. Fyld skraldespanden med bureaukrati — ikke penge!", argumentB: "NPM er GIFT for velfærden! Lad sygeplejersker og lærere gøre deres arbejde i stedet for at udfylde skemaer!", scoring: { optionA: { KF: 10, V: 9, LA: 8, M: 6, BP: 6 }, optionB: { SF: 10, S: 8, EL: 7, ALT: 6, RV: 5 } } },
  { id: 22, type: "faerre_penge_paa", category: "🇪🇺 EU vs. ✂️ Skat", optionA: "🇪🇺 Skær i EU-bidrag og internationale forpligtelser", optionB: "✂️ Fjern skattefordele og fradrag for høje indkomster", argumentA: "13,5 mia. kr. om året til Bruxelles. Hvad får VI egentlig ud af det? Pengene skal blive i DANMARK!", argumentB: "Topindkomster har MASSER af fradrag. Fjern dem og brug pengene på velfærd!", scoring: { optionA: { DF: 10, DD: 7, BP: 7, LA: 5, V: 4 }, optionB: { SF: 10, EL: 9, S: 8, ALT: 6, RV: 5 } } },
  { id: 23, type: "faerre_penge_paa", category: "🌿 Klima vs. ⚡ Elafgift", optionA: "🌿 Højere CO2-afgifter på alt fossilt", optionB: "⚡ Elafgift ned til EU-minimum — spar 6 mia. kr.", argumentA: "Planeten BRÆNDER. Højere afgifter er den eneste måde at tvinge omstillingen igennem.", argumentB: "Danskerne betaler EUROPAS højeste elpriser. Sænk afgiften og giv familier råd til varme!", scoring: { optionA: { ALT: 10, EL: 9, RV: 8, SF: 7 }, optionB: { LA: 10, KF: 7, V: 6, BP: 5, DD: 4 } } },
  { id: 24, type: "faerre_penge_paa", category: "🛒 Moms vs. 💸 Skat på arbejde", optionA: "🛒 Moms på mad halveres — frugt og grønt momsfrit", optionB: "💸 Sænke skat på arbejde og produktion", argumentA: "Sund mad skal IKKE koste en formue! Nul moms på frugt og grønt redder familiers økonomi.", argumentB: "Høj skat på arbejde gør det DYRERE at ansætte folk. Sænk skatten og få flere i job!", scoring: { optionA: { EL: 10, DF: 9, DD: 7, S: 6, ALT: 5 }, optionB: { M: 10, V: 8, LA: 8, KF: 6, BP: 5 } } },
  { id: 25, type: "faerre_penge_paa", category: "🌾 Landbrugsstøtte vs. ✂️ Offentlige udgifter", optionA: "🌾 Omdirigere landbrugsstøtte til klimastøtte", optionB: "✂️ Færre offentlige udgifter generelt — 15 mia. spart", argumentA: "5,3 mia. kr. til landmænd der forurener. OMDIRIGÉR pengene til grøn omstilling!", argumentB: "Staten er for FED! 15 mia. kr. i besparelser giver plads til skattelettelser for alle!", scoring: { optionA: { RV: 10, ALT: 9, EL: 8, SF: 7, S: 4 }, optionB: { LA: 10, KF: 8, V: 7, BP: 6, M: 5 } } }
];
